language: android

android:
  components:
    - tools                             # Tools
    - platform-tools                    # Platform tools
    - build-tools-25.0.2                # Build tools version
    - android-25                        # Target SDK version
    - extra-android-m2repository        # Support repo
    - sys-img-armeabi-v7a-android-18    # Emulator

jdk:
  - oraclejdk8

script:
#  - ./gradlew check jacocoTestReport coveralls sendCoverageToCodacy
#  - ./gradlew build
  - chmod +x ./gradlew

env:
  global:
    - secure: "SONATYPE_NEXUS_USERNAME TODO"

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle
before_install:
    - pip install --user codecov    #Install codecov

after_success:
    - codecov                       #Run codecov
